joinfaces:
  jsf:
    PROJECT_STAGE: Development
spring:
  profiles:
    active: "dev"

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: 'jdbc:h2:~/esig/dados'
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: false
        use_sql_comments: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
  output:
    ansi:
      enabled: always
  server:
  port: '8085'

---

spring:
  config:
      activate:
        on-profile: dev
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:postgresql://localhost:5432/task-manager'
    username: postgres
    password: 12345
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: false
        use_sql_comments: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  output:
    ansi:
      enabled: always

---

spring:
  config:
      activate:
        on-profile: prod
  main:
    banner-mode: off
  datasource:
    url: ${DATABASE_URL}
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false
        use_sql_comments: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
