joinfaces:
  jsf:
    PROJECT_STAGE: Development
spring:
  datasource:
    url: 'jdbc:h2:~/esig/dados'
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: false
        use_sql_comments: false
        format_sql: false
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
  output:
    ansi:
      enabled: always
server:
  port: '8080'

